# ==============================================================================
# Vaultwarden Secrets
# ==============================================================================
# IMPORTANT: Encrypt this file with SOPS before committing!
#   sops -e -i vaultwarden/secrets.yaml
#
# Generate admin token with: openssl rand -base64 48
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    labels:
        app.kubernetes.io/name: vaultwarden
type: Opaque
stringData:
    #ENC[AES256_GCM,data:j1EIFSCi2vW/gb3I0LGfpAZfimzx1KY6a2av3mpnJE2a/2aecRGRecUdvXMR1WJ4i6mYYA1JgTQcYs/aFiG3xtth,iv:Le8U2lPRwyQymw6gVVrBVoia+yUoF623oibFRbvD7pk=,tag:awYidHr1e4JwxNv2K1NxIQ==,type:comment]
    admin-token: ENC[AES256_GCM,data:bQmoVZns3+GN4RgInkdv1iBzVnfumWYSM/wa5coVPqUzZBml/sosUNHYss0iZQLXFoinXsp5LPYddnSukWI9eg==,iv:sZa8zMK60v3w54mL8YdmXo2MSgC2sXVQNMNLfv1QdV8=,tag:GEaCl/aVb+UkSWm4kFaetg==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQ3Rac25OVTlCdGJhbVBY
            R2xxZnREbnlmMkRYRkJUVUREaGlCZTMzQlU4CktZSGNSZ0E0RXMvYUh1UGdmSXZY
            TTJMV3JxTzBQZTJXYzl2a1g2eGljbU0KLS0tIHA5ZFU1ekRsVUdxTGZDdUY1cVJP
            U3M3V29UQ0R5TE9oR1Y4c2NsM2NERTQKA9m9JMTY1mB7ghgGauacpluaebr6WxBa
            csDuPOvHzAKOHpfpNvAZS2F9r8k7btEOatlJtgDrTm5RbTMROWeTNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T04:18:14Z"
    mac: ENC[AES256_GCM,data:zpmWRHI4qsEWp0dAd3WCs10HmtnARG65rTwZvyl9dSyTbEBuUxyVOQk3Zu7rzRPx0tP8zJ05j3AQq8uKMgvV3bLcnLfOOG0Qq28rkE44cdiajHTaAXC4+wP8NahpMNOXAxkJhv0QbHaXEWQNbAqH30sPM0nDmss1UjQ/dzkuseA=,iv:2a4sBKm7h23ZgpBeE+5HlvNNAe+pREAmzQRsizYs64w=,tag:4U1ewqN9XFOHPbC5sEePvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
