# ==============================================================================
# S3 Backup Credentials for CNPG
# ==============================================================================
# SeaweedFS S3 credentials for PostgreSQL backups
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: immich-db-backup-creds
    labels:
        app.kubernetes.io/name: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:hLMA+lA=,iv:SBtLxk5rj6YghS3SonJvgQxhxX4CLPT1SALOOjFzfZc=,tag:1yHG/8QC4eO5n9eCdyKsKA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BoDHLMI=,iv:oEXjottB7q2/2bfo/7IKa1xotx4lMMgctZmEFGXJdvY=,tag:45Z7UNHmtTk/9R/H5LArOw==,type:str]
sops:
    age:
        - recipient: age165ul5vra7q09yse7k0nharmt2jp0usw5tj2qwv2an9glyvxrr5ss5snxgj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMVhUNEgwa1ViQWFNTHgr
            UUNTRWhoVDBmTlJ2MVlxT3l5MXAxMDhOOURjCklkSWttd1Y2N1BzWU1yZ3E2VGp0
            SnpYSytNeXc2MnBvTzYreW5uTDdrY2sKLS0tIGRZemNEdGxHdktDLzBhVjFrTG56
            ZVppaVgyZ2s1QlJvVWxzVW83TDltVk0KrsfhzoZ+Umt77oolBYGRaiqQrAY3XzOX
            g+StBY07soANj2SuPEkgzPdl6YdKDx0rk60/pmHhmaRTI09dGuZtRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T05:43:30Z"
    mac: ENC[AES256_GCM,data:bYGMJQNFccHJvF8y1a2aUJJiCMhmACY6zt+MplPFvLeT3wAQVdvYYuiJe9we21y12b8izO6HxTt+H1B6hrv24uBFa+9mXekROOJ0grqwxAyqlyb8ghtTeUmJbYo2V+S8l7BA/bMqlcW5+lM4fYpWFf8Cecm+RAXZmVSlL++2TA0=,iv:BuYYcdPlyOOiONrs/pen+oY3U4t2mHZxIZUEHZx6GI4=,tag:qijtzKjJMcRHTsKrsXNQ/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
